#!/usr/bin/env python3
"""Dump the installed Omarchy themes' colour tokens into themes.js for the wireframes."""
import json, pathlib, tomllib

KEEP = ['mode', 'accent', 'selection', 'muted', 'background', 'dark_background', 'darker_background',
        'lighter_background', 'foreground', 'dark_foreground', 'light_foreground', 'bright_foreground',
        'red', 'yellow', 'orange', 'green', 'cyan', 'blue', 'magenta']
themes = {}
for d in sorted(pathlib.Path('/usr/share/omarchy/themes').iterdir()):
    f = d / 'colors.toml'
    if f.exists():
        t = tomllib.loads(f.read_text())
        themes[d.name] = {k: t[k] for k in KEEP if k in t}
out = pathlib.Path(__file__).with_name('themes.js')
out.write_text('// Generated by gen-themes.py from /usr/share/omarchy/themes/*/colors.toml.\n'
               'window.OMARCHY_THEMES = ' + json.dumps(themes, indent=1) + ';\n')
print(f'{len(themes)} themes -> {out.name}')
